# Generated by Django 3.2.12 on 2022-04-12 12:54

from django.db import migrations
from wagtail.core.models import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ('breads', '0004_auto_20220412_1254'),
    ]

    operations = [
        BootstrapTranslatableModel('breads.BreadIngredient'),
    ]
