# Generated by Django 3.2.12 on 2022-04-12 14:26

from django.db import migrations
from wagtail.core.models import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220412_1425'),
    ]

    operations = [
        BootstrapTranslatableModel('base.People'),
        BootstrapTranslatableModel('base.FooterText'),
    ]
